apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  namespace: app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: app
        image: registry.cluster.wik.cloud/public/echo
        ports:  
        - containerPort : 8080
